mirror-repository:
  image: bitnami/git

  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"

  before_script:
    - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
    - eval `ssh-agent -s`
    - echo "${SSH_PRIVATE_KEY}" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PUBLIC_KEY" >> ~/.ssh/id_rsa.pub
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - "echo 'TODO: Mirror Repository'"
    - git clone --mirror https://github.com/jojoxd/DXC-22-L.git upstream
    - cd upstream
    - git remote rm origin
    - git remote add origin ssh://git@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git push --prune --all
    - git push --prune --tags

variables:
  TARGET: NUCLEO_F303K8
  TOOLCHAIN: GCC_ARM

build:
  image: ghcr.io/armmbed/mbed-os-env:mbed-os-6-latest

  only:
    - branches
    - tags

  parallel:
    matrix:
      - DXC_TEAM: [1, 2, 3]

  artifacts:
    paths:
      - DXC-22-L-${CI_COMMIT_REF_SLUG}-TEAM-${DXC_TEAM}.bin

  script:
    # @TODO: Update
    - mbed deploy
    - mbed compile -t ${TOOLCHAIN} -m ${TARGET} -D DXC_TEAM=${DXC_TEAM} -D VERSION_STR "${CI_COMMIT_REF_SLUG}"
    - mv BUILD/${TARGET}/${TOOLCHAIN}/DXC-22-L.bin DXC-22-L-${CI_COMMIT_REF_SLUG}-TEAM-${DXC_TEAM}.bin
